### ISSUE TITLE
Click should only fire when mousedown/mouseup occur on the same item

### ISSUE THREAD

**Issue by arvind** [trifacta/vega#111]
Register these event listeners on the simple bar chart examples:
```javascript
ved.view.on('mousedown', function(e, i) { console.log('mousedown', i.key); });
ved.view.on('mouseup', function(e, i) { console.log('mouseup', i.key); });
ved.view.on('click', function(e, i) { console.log('click', i.key); });
```
Mousedown on one bar, move over to another bar and mouseup. See that all three events fire. With the DOM, the click would only fire if mousedown/mouseup occurred on the same element. 

Although, semantically, we're registering the event listeners on the entire view, they don't fire unless they occur over a specific item. So, in effect, events are implicitly registered on each individual item in the scene, and thus the click should follow convention.

**Comment by jheer** [comment]
Fixed in 4476e45e9c3f1d516963e3ede855ef9d321b096c.
