### ISSUE TITLE
Setting background color/opacity

### ISSUE THREAD

**Issue by iiSeymour** [trifacta/vega#191]
I couldn't find any reference in the documentation about setting the background colour/opacity of a chart?

**Comment by ianhoolihan** [comment]
I'd also love to see support for backgrounds. For now, @mprudhom's solution works well, though I've got group marks nested to three levels, which makes things a little messy! 

For now, I don't know the frameworks well enough to help with the coding, sorry. I've got a variety of charts which I'd be happy to test with though.

**Comment by jheer** [comment]
Thanks for all the comments here. I've added a new `background` property (which accepts a legal CSS color description, as recognized by `d3.rgb`) to the top-level of a Vega spec. This is now part of the v1.5.0 branch. The background currently supports solid colors only, though extensions to support opacity can be considered if necessary.

**Comment by ianhoolihan** [comment]
Awesome, thanks @jheer! I've just had a play -- am I right in thinking the background is set for the whole area, and not just the area contained within the axes? Unfortunately what I was looking for is the latter, as in @mprudhom's solution -- possibly I should have made this clearer, sorry.

**Comment by jheer** [comment]
You are correct: the new setting provides a global background. To cover only the axis region an enclosing group with its own background color can be used, as @mprudhom described.
