### ISSUE TITLE
Memory Leak using headless renderer

### ISSUE THREAD

**Issue by codazzo** [trifacta/vega#221]
Hi,

I'm using Vega in headless mode to render charts on the server with Node. I seem to have found an issue whereby every time I render a chart, some memory is leaked.  The example in https://gist.github.com/codazzo/5dd7310b8d2e612b59e7 exhibits this behaviour on my machine. It prints the memory usage after each time `render()` is called.

There seem to be some cleanup to be done with jsdom - the author suggests using `window.close()` although I haven't been able to find a suitable place in the source to do this.

Could anyone shed some light on this?
Cheers

**Comment by jheer** [comment]
As of v1.5.0, JSDOM is no longer used for SVG rendering.
