### ISSUE TITLE
Not possible to set the number of ticks on the x axis of a default bar chart

### ISSUE THREAD

**Issue by superneko** [trifacta/vega#230]
Hey there!

It doesn't seem to be possible to set the number of ticks on the x axis of a bar chart. 
I also tried in the Vega editor and it works just fine with line charts but not so with the simple bar chart.

The thing is that we need to be able to display fewer ticks for some date as the labels start overlapping at some point (see screenshot below) - being able to show fewer ticks should do the trick just fine.

![screen shot 2015-01-21 at 17 37 29](https://cloud.githubusercontent.com/assets/1322687/5840260/661c850e-a194-11e4-995b-85cbb61417d9.png)

Right now our solution is to just add "empty" labels to the chart (see screenshot below), but that feels kind of odd. 

![screen shot 2015-01-21 at 17 40 03](https://cloud.githubusercontent.com/assets/1322687/5840282/a15b2710-a194-11e4-89c1-f9a69af05fab.png)

Is this a bug (or feature) or is there actually any smarter way to make this work?

Cheers

**Comment by jheer** [comment]
One option is to set the `ticks` property on your axis definition. This serves as a "suggestion", but __not__ a hard constraint, to the tick generator. The actual implementation simply passes this parameter down to a `d3` scale object. Note that this parameter applies to quantitative and time scales, but not ordinal scales.

Another option is to explicitly set the visible tick values using the axis `values` property. This is useful for cases where you are comfortable "hard-wiring" the set of axis labels.

Finally, in some cases you might improve tick legibility without lowering the number of ticks by rotating the axis labels. For example, within an axis definition you can write:
```
"properties": {
  "labels": {
    "angle": {"value": -45},
    "align": {"value": "right"}
  }
}
```

For more, see the relevant wiki page: https://github.com/trifacta/vega/wiki/Axes
