### ISSUE TITLE
Sanitize output for headless SVG generation

### ISSUE THREAD

**Issue by mprudhom** [trifacta/vega#240]
The new direct SVG generation feature in the v1.5.0 branch is fantastic; it is orders of magnitude faster now that it doesn't need to go through a fake DOM.

However, the SVG generation needs to consider escaping special characters in order to generate valid XML. For example, a visualization that contains the text "ANGLE<BRACKET" will generate malformed XML, as seem with the following command:

```shell
09:56 vega$ echo '{ "marks": [ { "type": "text", "properties": { "enter": { "text": {"value": "ANGLE<BRACKET"} } } } ] }' > unescaped.json && ./bin/vg2svg unescaped.json | xmllint -
```

Which will yield:

```output
-:1: parser error : error parsing attribute name
" y="0" text-anchor="start" style="fill:none;font:11px sans-serif">ANGLE<BRACKET
                                                                               ^
-:1: parser error : attributes construct error
" y="0" text-anchor="start" style="fill:none;font:11px sans-serif">ANGLE<BRACKET
                                                                               ^
-:1: parser error : Couldn't find end of Start Tag BRACKET line 1
" y="0" text-anchor="start" style="fill:none;font:11px sans-serif">ANGLE<BRACKET
                                                                               ^
```

Let me know if you are interested in a pull request for this and I'll work on it.

**Comment by jheer** [comment]
Thanks! Fixed (with matching test case) in 6ee18d615598338f5eb5e0c2641f3a6467c5c6dd.

**Comment by mprudhom** [comment]
One other place you should use `escape_text` is in the attribute values, in case, for example, the font-face name has a funky character. See my patch at <https://github.com/trifacta/vega/pull/241/files>

**Comment by jheer** [comment]
Thanks! Font names are actually subject to different rules according to the CSS spec. Many of the "funky" characters are not allowed (if unquoted), and in any case HTML escapes are not used. However, your comment did cause me to realize that embedded double quotes could cause an issue, so I pushed a fix for that.
