### ISSUE TITLE
Fallbacks on invalid data

### ISSUE THREAD

**Issue by ferdbold** [trifacta/vega#282]
Is there some way of making sure a spec is valid before sending it to Vega (like some sort of vg.validate method)? I'm currently working on a graph editing UI powered by Vega and right now invalid data results in undesirable JS errors.

For example, with a basic stacked area graph, sending this data:

{ x: 0, y: 28, c: 1 },
{ x: 0, y: 55, c: 1 },
{ x: 1, y: 43, c: 0 },
{ x: 1, y: 91, c: 1 },
{ x: 2, y: 81, c: 0 },
{ x: 2, y: 53, c: 1 }

will result in errors due to the first point not being set to c: 0. It will trigger some unhelpful errors about out of range arguments, both on render and on mouse over. Vega should at least be able to fallback on some more relevant errors about what exactly went wrong with the parsing.

**Comment by jheer** [comment]
Validation is not supported in Vega 1.5, but Vega 2.0 includes a JSON
schema that can be used for validation.

Vega 2 is under development here: https://github.com/uwdata/vega/tree/v2

We plan to move Vega 2 over to the primary repo within the coming month.

However, schema validation will not solve problems with value-based
bugs/errors/anomalies in the input data set...

**Comment by ferdbold** [comment]
Whoops, didn't notice there was a 2.0 version in development.

I suppose data validation is something that can be handled on my end, since end users will not directly manipulate the spec but rather use a UI that will take care of generating it.

Thanks for the quick reply!
